#!/bin/bash

test_description='Sanity checks'
source $(dirname $0)/setup.sh

test_expect_success 'Make sure we can run `ls`' '
    ls -al
'

test_expect_success 'Make sure we can run `pwd`' '
    pwd
'

test_done
